name: ip-scanner-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - opencv-python>=4.0.0
    - Pillow>=8.0.0
    - pytest>=7.0.0
    - pytest-cov>=4.0.0
    - requests>=2.25.0
